import json
from io import BytesIO
from pathlib import Path
from typing import Callable, Dict, List, Optional, Tuple

from PIL import Image, ImageOps


def _read_image_size(image_path: Path) -> Tuple[int, int]:
    with Image.open(BytesIO(image_path.read_bytes())) as img:
        img = ImageOps.exif_transpose(img)
        return img.width, img.height


def export_coco(
    image_paths: List[Path],
    annotations_by_image: Dict[str, List[Dict]],
    categories: List[Dict],
    size_cache: Dict[str, Tuple[int, int]],
    output_path: Path,
) -> Tuple[int, int]:
    """Write COCO JSON. Uses size_cache to avoid re-reading every image."""
    images = []
    image_id_by_name: Dict[str, int] = {}

    for idx, img_path in enumerate(image_paths, start=1):
        w, h = size_cache.get(img_path.name) or _read_image_size(img_path)
        image_id_by_name[img_path.name] = idx
        images.append({"id": idx, "file_name": img_path.name, "width": w, "height": h})

    annotations = []
    ann_id = 1
    for image_name, anns in annotations_by_image.items():
        img_id = image_id_by_name.get(image_name)
        if img_id is None:
            continue
        for ann in anns:
            x, y, w, h = ann["bbox"]
            if w <= 0 or h <= 0:
                continue
            annotations.append(
                {
                    "id": ann_id,
                    "image_id": img_id,
                    "category_id": int(ann["category_id"]),
                    "bbox": [round(float(x), 2), round(float(y), 2), round(float(w), 2), round(float(h), 2)],
                    "area": round(float(w * h), 2),
                    "iscrowd": 0,
                    "segmentation": [],
                }
            )
            ann_id += 1

    coco = {
        "info": {"description": "YOLOX COCO annotations generated by PySide6 annotator"},
        "licenses": [],
        "images": images,
        "annotations": annotations,
        "categories": categories,
    }
    output_path.write_text(json.dumps(coco, ensure_ascii=False, indent=2), encoding="utf-8")
    return len(images), len(annotations)


def import_coco(
    path: Path,
    valid_image_names: set,
    category_name_by_id: Callable[[int], str],
) -> Tuple[Optional[List[Dict]], Dict[str, List[Dict]], int]:
    """
    Parse a COCO JSON file.

    Returns:
        categories  – list of category dicts (or None if absent in JSON)
        annotations_by_image – keyed by file_name, only valid images included
        max_ann_id  – highest annotation id seen (for continuing id sequence)
    """
    data = json.loads(path.read_text(encoding="utf-8"))

    categories: Optional[List[Dict]] = None
    if "categories" in data:
        categories = [{"id": int(c["id"]), "name": str(c["name"])} for c in data["categories"]]

    image_name_by_id = {int(img["id"]): img["file_name"] for img in data.get("images", [])}
    annotations_by_image: Dict[str, List[Dict]] = {name: [] for name in valid_image_names}
    max_ann_id = 0

    for ann in data.get("annotations", []):
        image_name = image_name_by_id.get(int(ann["image_id"]))
        if image_name not in valid_image_names:
            continue
        cat_id = int(ann["category_id"])
        ann_id = int(ann.get("id", max_ann_id + 1))
        max_ann_id = max(max_ann_id, ann_id)
        x, y, w, h = ann["bbox"]
        annotations_by_image[image_name].append(
            {
                "id": ann_id,
                "image_name": image_name,
                "category_id": cat_id,
                "category_name": category_name_by_id(cat_id),
                "bbox": [float(x), float(y), float(w), float(h)],
                "area": float(w * h),
                "iscrowd": int(ann.get("iscrowd", 0)),
            }
        )

    return categories, annotations_by_image, max_ann_id
